version: '3'
services:
  web:
    build: .
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - DATABASE_URL=postgres://hubble:insecure@db
      - CLIENT_CONFIG_URL=https://raw.githubusercontent.com/vanhacks-hubble/python-hubble-config/master/config.yml
    volumes:
      - .:/api
    links:
      - db
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=hubble
      - POSTGRES_PASSWORD=insecure
