version: '3'
services:
  web:
    build: .
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - DATABASE_URL=postgres://db
    volumes:
      - .:/api
    links:
      - db
  db:
    image: postgres
